#!/usr/bin/env python3
"""
Emit intrinsic dimensions for every image in web/public/img.

next/image needs width and height for anything that is not `fill`, and the
case-study figures cannot use `fill`: their CSS is height:auto with a
max-height clamp. Reading the dimensions out of the file headers means the
figures still get srcset, AVIF/WebP and lazy loading, instead of falling
back to a plain <img>.

Run from the repo root:   python3 web/scripts/image_sizes.py
"""
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
IMG_DIR = os.path.join(ROOT, "web", "public", "img")
OUT = os.path.join(ROOT, "web", "content", "image-sizes.ts")


def png_size(f):
    head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])


def jpeg_size(f):
    f.seek(0)
    if f.read(2) != b"\xff\xd8":
        return None
    while True:
        b = f.read(1)
        if not b:
            return None
        if b != b"\xff":
            continue
        # skip fill bytes
        marker = f.read(1)
        while marker == b"\xff":
            marker = f.read(1)
        if not marker:
            return None
        m = marker[0]
        # SOF0..SOF15, excluding DHT(C4), JPG(C8), DAC(CC)
        if 0xC0 <= m <= 0xCF and m not in (0xC4, 0xC8, 0xCC):
            f.read(3)  # length(2) + precision(1)
            h, w = struct.unpack(">HH", f.read(4))
            return w, h
        seg = f.read(2)
        if len(seg) < 2:
            return None
        length = struct.unpack(">H", seg)[0]
        f.seek(length - 2, os.SEEK_CUR)


def dimensions(path):
    """Sniff by magic bytes, not by extension.

    Several files in this project are mislabelled: project-*.png are
    actually JPEGs and profile-photo.jpg is actually a PNG. Browsers sniff
    content and cope; trusting the extension here would not.
    """
    with open(path, "rb") as f:
        magic = f.read(8)
        f.seek(0)
        if magic.startswith(b"\x89PNG\r\n\x1a\n"):
            return png_size(f)
        if magic.startswith(b"\xff\xd8"):
            return jpeg_size(f)
    return None


def main():
    sizes = {}
    skipped = []

    for dirpath, _, files in os.walk(IMG_DIR):
        for name in sorted(files):
            if not name.lower().endswith((".png", ".jpg", ".jpeg")):
                continue
            full = os.path.join(dirpath, name)
            rel = "/" + os.path.relpath(full, os.path.join(ROOT, "web", "public")).replace(os.sep, "/")
            dim = dimensions(full)
            if dim:
                sizes[rel] = dim
            else:
                skipped.append(rel)

    lines = [
        "// ─────────────────────────────────────────────────────────────────────────",
        "// GENERATED by web/scripts/image_sizes.py. Do not edit by hand.",
        "// Intrinsic dimensions, so next/image can optimise figures that cannot",
        "// use `fill` (their CSS is height:auto with a max-height clamp).",
        "// ─────────────────────────────────────────────────────────────────────────",
        "",
        "export const imageSizes: Record<string, { width: number; height: number }> = {",
    ]
    for path, (w, h) in sorted(sizes.items()):
        lines.append(f"  '{path}': {{ width: {w}, height: {h} }},")
    lines.append("}")
    lines.append("")
    lines.append("/** Falls back to a 3:2 box if an image is missing from the map. */")
    lines.append("export function sizeOf(src: string) {")
    lines.append("  return imageSizes[src] ?? { width: 1200, height: 800 }")
    lines.append("}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"  {os.path.relpath(OUT, ROOT)}  ({len(sizes)} images)")
    if skipped:
        print("  ⚠ could not read:", ", ".join(skipped))


if __name__ == "__main__":
    main()
