'use client'
/* CMS assets require per-request authorization and bypass the public optimizer. */
/* eslint-disable @next/next/no-img-element */
import { useCallback,useEffect,useState } from 'react'
import Link from 'next/link'
import { api } from './api'
import { FieldTree } from './Fields'
interface MediaItem{id:string;name:string;mime:string;bytes:number;width:number|null;height:number|null;alt:string;caption:string;labels:string[];focalX:number;focalY:number;trashedAt:string|null;createdAt:string}
interface Upload{file:File;progress:number;error?:string;done?:boolean}
export function MediaLibrary(){
 const [items,setItems]=useState<MediaItem[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[trash,setTrash]=useState(false),[view,setView]=useState('grid'),[error,setError]=useState(''),[selected,setSelected]=useState<MediaItem|null>(null),[uploads,setUploads]=useState<Upload[]>([]),[usage,setUsage]=useState<{entryId:string;visibility:string}[]>([]),[crop,setCrop]=useState({left:0,top:0,width:1,height:1})
 const reload=useCallback(()=>api<MediaItem[]>('media').then(setItems),[])
 useEffect(()=>{void reload().catch(e=>setError(e.message))},[reload])
 async function upload(file:File){setUploads(rows=>[...rows.filter(r=>r.file!==file),{file,progress:0}]);try{await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/admin/media');xhr.upload.onprogress=e=>{if(e.lengthComputable)setUploads(rows=>rows.map(r=>r.file===file?{...r,progress:Math.round(e.loaded/e.total*100)}:r))};xhr.onerror=()=>reject(new Error('Koneksi upload terputus'));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve();else{if(xhr.status===401)window.dispatchEvent(new CustomEvent('cms-session-expired'));try{reject(new Error(JSON.parse(xhr.responseText).error))}catch{reject(new Error('Upload gagal'))}}};const body=new FormData();body.append('file',file);xhr.send(body)});setUploads(rows=>rows.map(r=>r.file===file?{...r,done:true,progress:100}:r));await reload()}catch(e){setUploads(rows=>rows.map(r=>r.file===file?{...r,error:(e as Error).message}:r))}}
 async function choose(m:MediaItem){setSelected(m);setUsage([]);setCrop({left:0,top:0,width:m.width??1,height:m.height??1});try{setUsage(await api(`media/${m.id}/usage`))}catch(e){setError((e as Error).message)}}
 async function action(task:()=>Promise<unknown>){setError('');try{await task();setSelected(null);await reload()}catch(e){setError((e as Error).message)}}
 const filtered=items.filter(m=>!!m.trashedAt===trash&&m.mime.startsWith(kind)&&`${m.name} ${m.labels.join(' ')} ${m.createdAt}`.toLowerCase().includes(query.toLowerCase()))
 return <><div className="cms-toolbar"><div className="cms-actions"><input aria-label="Cari media, label, tanggal" placeholder="Cari media, label, tanggal…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Jenis media" value={kind} onChange={e=>setKind(e.target.value)}>{[['','Semua jenis'],['image/','Gambar'],['video/','Video'],['audio/','Audio'],['application/pdf','PDF']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button aria-pressed={trash} onClick={()=>setTrash(!trash)}>Trash</button><button onClick={()=>setView(view==='grid'?'list':'grid')}>{view==='grid'?'Tampilan daftar':'Tampilan grid'}</button></div><label className="cms-upload-button">+ Upload<input multiple type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif,video/mp4,video/webm,audio/*,application/pdf" onChange={async e=>{const files=Array.from(e.target.files??[]);for(const file of files)await upload(file)}}/></label></div>{error&&<p className="cms-alert" role="alert">{error}</p>}{uploads.map((u,i)=><div key={i} role="status"><span>{u.file.name} · {u.done?'Selesai':`${u.progress}%`}</span>{!u.done&&!u.error&&<progress value={u.progress} max={100}/>} {u.error&&<><span>{u.error}</span><button onClick={()=>void upload(u.file)}>Coba lagi</button></>}</div>)}<div className={view==='grid'?'cms-media-grid':'cms-lines'}>{filtered.map(m=><button key={m.id} onClick={()=>void choose(m)}>{!trash&&m.mime.startsWith('image/')?<img src={`/media/${m.id}/w320.webp`} alt={m.alt}/>:<span>{m.mime}</span>}<strong>{m.name}</strong><small>{(m.bytes/1024).toFixed(0)} KB · {new Date(m.createdAt).toLocaleDateString()}</small></button>)}</div>{!filtered.length&&<div className="cms-empty"><h2>Tidak ada media pada filter ini</h2><p>Upload file atau ubah pencarian untuk melanjutkan.</p></div>}
 {selected&&<div className="cms-modal-backdrop"><section className="cms-dialog" role="dialog" aria-modal="true" aria-label="Detail media"><h2>{selected.name}</h2>{error&&<p role="alert" className="cms-alert">{error}</p>}{!selected.trashedAt&&selected.mime.startsWith('image/')&&<img src={`/media/${selected.id}/w960.webp`} alt={selected.alt} style={{width:'100%',maxHeight:260,objectFit:'contain'}}/>}<FieldTree value={{alt:selected.alt,caption:selected.caption,labels:selected.labels,focalX:selected.focalX,focalY:selected.focalY}} onChange={v=>setSelected({...selected,...v as object})}/><p><code>/media/{selected.id}/original</code></p><h3>Digunakan pada</h3>{usage.length?<ul>{usage.map((u,i)=><li key={i}><Link href={`/admin/edit/${u.entryId}`}>Buka konten</Link> · {u.visibility}</li>)}</ul>:<p>Belum direferensikan konten aktif. Revisi lama tetap dilindungi.</p>}{!selected.trashedAt&&selected.mime.startsWith('image/')&&<details><summary>Crop sebagai versi baru</summary><FieldTree value={crop} onChange={v=>setCrop(v as typeof crop)}/><p>Koordinat dalam piksel. Original dan halaman published tetap memakai versi sebelumnya.</p><button onClick={()=>void action(async()=>{const result=await api<{url:string}>(`media/${selected.id}/crop`,'POST',crop);alert(`Versi crop dibuat: ${result.url}. Pilih versi baru pada draft konten.`)})}>Buat crop</button></details>}<div className="cms-actions"><button onClick={()=>setSelected(null)}>Tutup</button>{selected.trashedAt?<><button onClick={()=>void action(()=>api(`media/${selected.id}/restore`,'POST',{}))}>Pulihkan</button><button onClick={()=>{if(confirm('Hapus file ini secara permanen?'))void action(()=>api(`media/${selected.id}?permanent=1`,'DELETE'))}}>Hapus permanen</button></>:<><button onClick={()=>void action(()=>api(`media/${selected.id}`,'PUT',{alt:selected.alt,caption:selected.caption,labels:selected.labels,focalX:selected.focalX,focalY:selected.focalY}))}>Simpan metadata</button><button onClick={()=>{if(confirm('Pindahkan media yang tidak dipakai ke trash?'))void action(()=>api(`media/${selected.id}`,'DELETE'))}}>Trash</button></>}</div></section></div>}</>
}
