// ─────────────────────────────────────────────────────────────────────────
// GENERATED by web/scripts/port_content.py. Do not edit by hand.
// Re-run the script if the Flask source changes; otherwise edit this file
// directly and delete the script once the Flask app is archived.
// ─────────────────────────────────────────────────────────────────────────
import type { CaseStudy } from '@/lib/types'
import { bobbinSensorDoe } from './bobbin-sensor-doe'
import { juraganCipung } from './juragan-cipung'
import { kopitechDashboard } from './kopitech-dashboard'
import { ensyseProject } from '../project-details/ensyse-website'
import { qseDesignPortfolio } from '../design-portfolios/qse-design-portfolio'

export const caseStudies: Record<string, CaseStudy> = {
  'bobbin-sensor-doe': bobbinSensorDoe,
  'juragan-cipung': juraganCipung,
  'kopitech-dashboard': kopitechDashboard,
  'ensyse-website': ensyseProject,
  'qse-instagram-redesign': qseDesignPortfolio,
}
