// ─────────────────────────────────────────────────────────────────────────
// GENERATED by web/scripts/port_content.py. Do not edit by hand.
// Re-run the script if the Flask source changes; otherwise edit this file
// directly and delete the script once the Flask app is archived.
// ─────────────────────────────────────────────────────────────────────────
import type { PlaygroundItem } from '@/lib/types'

export const playground: PlaygroundItem[] = [
  {
    slug: 'offtheclock',
    title: 'Off the Clock',
    premise: 'A little pixel island for my homelab, music, films, and games.',
    medium: 'Interactive world',
    status: 'experiment',
    preview: '/img/off-the-clock/intro/illustrated/title-island.webp',
    previewWidth: 1354,
    previewHeight: 657,
    learning: 'Wander through the island, collections, journals, and small activities.',
    destination: '/playground/offtheclock',
    destinationType: 'internal',
    playgroundRank: 1,
    listedAt: '2026-09-26',
  },
]
