// ─────────────────────────────────────────────────────────────────────────
// GENERATED by web/scripts/port_content.py. Do not edit by hand.
// Re-run the script if the Flask source changes; otherwise edit this file
// directly and delete the script once the Flask app is archived.
// ─────────────────────────────────────────────────────────────────────────
import type { Profile } from '@/lib/types'

export const profile: Profile = {
  fullName: "David Rizky Wijaya",
  displayName: "David",
  roleTitle: "Industrial Engineering Fresh Graduate",
  shortBio: "Currently open to opportunities and available to work across Indonesia.",
  bio: "I am a fresh Industrial Engineering graduate from Telkom University with experience in procurement, supplier performance management, data analysis, business process improvement, ERP, and digital system development through my internship at Telkom Indonesia’s Group Procurement Center and various academic projects. I am particularly interested in Operational Excellence, Supply Chain and Procurement, ERP and Business Analysis, Process Improvement, and Data Analytics, where I can apply structured and data-driven approaches to improve business and operational performance.",
  statusLabel: "ESP32 Bobbin Thread Detection System",
  photo: "/img/profile/profile-photo.jpg",
  email: "davidrwijaya@gmail.com",
  linkedinUrl: "https://www.linkedin.com/in/david-rizky-wijaya-a9b840125/",
  githubUrl: "https://github.com/drwijaya",
  instagramUrl: "https://www.instagram.com/davidrwijaya/",
  cvUrl: "https://drive.google.com/file/d/1YqD4J6pOAEUgYKWycRUNyv1i9FYDuWon/view",
  updatedAt: "2026-08-23",
}
