// ─────────────────────────────────────────────────────────────────────────
// Source of truth. The porter scripts were deleted with the Flask app;
// edit this file directly.
// ─────────────────────────────────────────────────────────────────────────
import type { Project } from '@/lib/types'

export const projects: Project[] = [
  {
    slug: "bobbin-sensor-doe",
    title: "Designing a Bobbin Run-Out Detector, Testing Its Placement",
    presentationType: "case-study",
    practice: "Operations & Quality",
    sector: "Manufacturing",
    projectType: "Academic",
    cardStatement:
      "I built a sensor that warns before a sewing bobbin runs dry, then ran a 2\u00B2 factorial experiment to fix where it should be mounted.",
    categoryColor: "terracotta",
    year: "2026",
    status: "published",
    methods: ["Design of Experiments", "ANOVA", "Prototyping"],
    deliverables: ["Detection Prototype", "Mounting Spec", "DOE Analysis"],
    tools: ["ESP32", "Arduino C++", "Python"],
    thumb: "/img/case-studies/bobbin-sensor-doe/bobbinTHUMB.png",
    tileRatio: "16/9",
    portfolioRank: 1,
    proofLevel: "E2",
    githubUrl: "https://github.com/drwijaya/bobbinmonitor",
    detailSlug: "bobbin-sensor-doe",
  },
  {
    slug: "juragan-cipung",
    title: "Quality Control SOP & Dashboard",
    presentationType: "case-study",
    practice: "Operations & Quality",
    sector: "Manufacturing",
    projectType: "Capstone",
    cardStatement:
      "Our team moved quality checks into six production stages and delivered an approved SOP and dashboard, validated through 184 UAT cases.",
    categoryColor: "terracotta",
    year: "2026",
    status: "published",
    methods: ["Process Improvement", "ISO 9001:2015", "BPMN"],
    deliverables: ["QC SOP", "Control Forms", "Dashboard"],
    tools: ["Flask", "PostgreSQL"],
    thumb: "/img/case-studies/juragan-cipung/thumbCipung.png",
    tileRatio: "16/9",
    portfolioRank: 2,
    proofLevel: "E2",
    detailSlug: "juragan-cipung",
  },
  {
    slug: "kopitech-dashboard",
    title: "Kopitech Corp Integrated Dashboard",
    presentationType: "case-study",
    practice: "Systems Analysis",
    sector: "Manufacturing",
    projectType: "Academic",
    cardStatement:
      "Our team mapped nine production roles and translated the proposed process into 28 dashboard features with 27 acceptance criteria.",
    categoryColor: "dusty-blue",
    year: "2025",
    status: "published",
    methods: ["Systems Analysis", "BPMN", "Requirements"],
    deliverables: ["Process Model", "Access Matrix", "Dashboard"],
    tools: ["Node.js"],
    thumb: "/img/case-studies/kopitech-dashboard/ui-dashboard.png",
    tileRatio: "16/9",
    portfolioRank: 3,
    proofLevel: "E1",
    detailSlug: "kopitech-dashboard",
  },
  {
    slug: "ensyse-website",
    title: "ENSYSe Laboratory Website",
    presentationType: "case-study",
    practice: "Digital Product",
    sector: "Education",
    projectType: "Laboratory",
    cardStatement:
      "I led product design and built a WordPress front end that gave the ENSYSe laboratory one editable public website.",
    categoryColor: "sage",
    year: "2026",
    status: "published",
    methods: ["Product Design", "Information Architecture", "Scrum"],
    deliverables: ["Figma Page System", "WordPress Website", "Gutenberg Blocks"],
    tools: ["Figma", "HTML/CSS/JS", "WordPress"],
    thumb: "/img/case-studies/ensyse-website/thumb.png",
    tileRatio: "16/9",
    portfolioRank: 4,
    proofLevel: "E1",
    demoUrl: "https://ensys.labs.telkomuniversity.ac.id",
    detailSlug: "ensyse-website",
  },
  {
    slug: "qse-instagram-redesign",
    title: "QSE Design Portfolio",
    presentationType: "case-study",
    practice: "Visual Systems",
    sector: "Professional Organization",
    projectType: "Organization",
    cardStatement:
      "A selected collection of recruitment, internship, team, and event designs built from one shared visual system for QSE.",
    categoryColor: "mustard",
    year: "2025",
    status: "published",
    methods: ["Visual Direction", "Layout System", "Art Direction"],
    deliverables: ["Master Template", "Campaign Collections", "Content Pillars"],
    tools: ["Figma", "Photoshop"],
    thumb: "/img/case-studies/qse-instagram-redesign/figma-cover.jpg",
    tileRatio: "16/9",
    portfolioRank: 5,
    proofLevel: "E1",
    projectUrl: "https://www.instagram.com/keprofqse_/",
    detailSlug: "qse-instagram-redesign",
  },
]
